apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatterbox-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatterbox-mysql
  template:
    metadata:
      labels:
        app: chatterbox-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        environment: {}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "mysql"
        - name: MYSQL_DATABASE
          value: "chatterbox_db"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: chatterbox-mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: chatterbox-mysql
